#!/bin/bash
rpath="$(readlink ${BASH_SOURCE})"
if [ -z "$rpath" ];then
    rpath=${BASH_SOURCE}
fi
me="$(cd $(dirname $rpath) && pwd)"
cd "$me"

echo "install go binaries..."
echo "VIM: $VIM"
echo "root: $root"
$VIM -c GoInstallBinaries -c qall
cp coc-settings.json $root
echo "go binaries done"
