#!/bin/bash

if [[ "$(uname)" != "Darwin" ]];then
    echo "Not macOS"
    exit 1
fi

#install homebrew
if ! command -v brew >/dev/null;then
    echo "install homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

shopt -s expand_aliases
alias brew='ALL_PROXY=socks5://localhost:1080 brew'
apps="coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt gnu-which wget go neovim vim python python3 privoxy aria2"
for app in $apps;do
    if ! brew list $app >/dev/null 2>&1;then
        echo "Install $app..."
        brew install $app
    fi
done
#BREW install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt gnu-which wget go neovim vim python python3 privoxy aria2
SBIN=$(find /usr/local/Cellar/privoxy -name "sbin")
ln -sf  $SBIN/privoxy /usr/local/bin/privoxy
pkill privoxy
brew tap homebrew/dupes;
brew install grep

