#!/bin/bash
if [[ "$(uname)" != "Darwin" ]];then
    echo "Not macOS"
    exit 1
fi

function usage(){
    echo "dev-mac [options]"
    echo "options:"
    echo "-l    local proxy,ie socks5://localhost:1080"
    echo "-p   [URL of proxy] socks5 or http proxy"
    exit 0
}

USER=${SUDO_USER:-$(whoami)}
proxy=
while getopts ":hlp:" opt;do
    case "$opt" in
        h)
            usage
            ;;
        l)
            proxy=socks5://localhost:1080
            ;;
        p)
            proxy=$OPTARG
            ;;
        :)
            echo "option: '$OPTARG' need argument!!"
            exit 1
            ;;
        \?)
            echo "option: '$OPTARG' not supported!!"
            exit 1
            ;;
    esac
done

if [[ -n "$proxy" ]];then
    echo "using proxy: $proxy"
    shopt -s expand_aliases

    #set brew proxy
    alias brew="ALL_PROXY=$proxy brew"
    #set curl proxy
    #curl -x or curl --proxy or http_proxy environment variable
    #support http or socks5 proxy
    alias curl="curl -x $proxy"
    #set git proxy
    git config --global http.proxy "$proxy"

    #set wget proxy
    export http_proxy="$proxy"
    export https_proxy="$proxy"
    export ftp_proxy="$proxy"

    export HTTP_PROXY="$proxy"
    export HTTPS_PROXY="$proxy"
    export FTP_PROXY="$proxy"
fi
#install homebrew
#if ! command -v brew >/dev/null;then
if [[ ! -e /usr/local/bin/brew ]];then
    echo "install homebrew..."
    su $USER -c "curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install|/usr/bin/ruby"
    #/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || { echo "Install homebrew failed!"; exit 1; }
fi

#apps="coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt gnu-which wget go neovim vim python python3 privoxy aria2"
apps="coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt gnu-which wget go neovim vim python python3 privoxy"
for app in $apps;do
    if ! brew list $app >/dev/null 2>&1;then
        echo "Install $app..."
        if [[ -n ${SUDO_USER} ]];then
            su $USER -c "brew install $app"
        else
            brew install $app
        fi
    fi
done
#BREW install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt gnu-which wget go neovim vim python python3 privoxy aria2
SBIN=$(find /usr/local/Cellar/privoxy -name "sbin")
ln -svf  $SBIN/privoxy /usr/local/bin/privoxy
pkill privoxy
#brew tap homebrew/dupes;
if [[ -n ${SUDO_USER} ]];then
    su $USER -c "brew install grep"
else
    brew install grep
fi
