#!/bin/bash
if [[ $EUID -ne 0 ]];then
    echo "Need root privilege!"
    exit 1
fi

if ! command -v apt >/dev/null 2>&1;then
    echo "Only run on debian."
    exit 1
fi

apt update
apt install -y samba samba-common
mv /etc/samba/smb.conf{,.bak}

groupadd smbadmin -f
groupadd smbuser -f

mkdir -p /home/public
chown root:smbadmin /home/public
chmod 775 /home/public

cat>/etc/samba/smb.conf<<EOF
[global]
workgroup = WORKGROUP
server string = Samba Server %v
netbios name = debian samba
security = user
map to guest = never
dns proxy = no

[homes]
comment = Home Directories
browsable = no
valid users = %S
writable = yes
create mask = 0700
directory mask = 0700

[public]
comment = All Users can access
path = /home/public
valid users = @smbuser, @smbadmin
force group = smbuser
create mask = 0744
directory mask = 0755
writable = no
write list = @smbadmin
EOF

addSmbUser(){
    if [[ $# -ne 2 ]];then
        echo "Usage: $(basename $0) user group"
    fi
    userlist=$(awk -F: '{print $1}' /etc/passwd)
    user=$1
    group=$2
    if grep -q $user <<< $userlist;then
        echo "$user already exists,add it to group $group..."
        usermod -a -G $group $user
    else
        echo "$user doesn't exist,create it and add it to group $group.."
        useradd $user -m -G $group
        echo "Enter password for user: $user"
        passwd $user
    fi
    echo "Enter smb password for user: $user"
    smbpasswd -a $user
}
systemctl restart smbd.service

#add administrator
addSmbUser eagle smbadmin

#add user1
addSmbUser user1 smbuser
#reference https://www.howtoforge.com/tutorial/debian-samba-server/
#https://www.samba.org/samba/docs/man/manpages-3/smb.conf.5.html
